### ISSUE TITLE
Prompt creations for APIs  

### ISSUE THREAD

**Issue by TjRaffert** [alejmedinajr/AI-Detector#15]
The prompt we give to each model is important for the results.

**Comment by TjRaffert** [comment]
I have stated working on this in the drive

**Comment by TjRaffert** [comment]
I am doing some experimenting with chatgpt. I think we should also have a place to submit instructions like the readme separate from the blank assignment. I am also realizing that we are going to run into some issues when generating the necessary amount of responses. If we say generate 10 different responses it will only give 3 or 4 because it has some internal limit to make the model cheaper. I think the best way to overcome this is to make a loop that asks for a different response each time parsing the code from every individual response. I spent 45 minutes

**Comment by TjRaffert** [comment]
I spent 30 minutes finishing up some practice prompts and testing them out. Here is a doc with some recommended prompts.https://docs.google.com/document/d/1gq1b-M-R98RMH7byFkWkNM3PF5pBedst_GdrOIIObnw/edit

**Comment by TjRaffert** [comment]
I am going to do A little more experimenting with this.

**Comment by TjRaffert** [comment]
I spent 30 minutes checking if this will work and it does. I also discovered that if you specify to respond with the code only it will do that. I am now going to see if it works with bard.

**Comment by TjRaffert** [comment]
I spent 15 minutes making sure Bard would respond in the same way. It functions exactly the same as chatgpt. We also need to make sure the code it spits out is put in these code boxes and I don't know if it functions as normal text. I also think we should have a place to toggle the programing language into the prompt.

**Comment by alejmedinajr** [comment]
I am going to break this issue into three different issues. The reasoning is that the idea of creating custom prompts is already something the users have the ability to do. Instead of doing this in the code, we should have a guide that tells the users good practices (as mentioned in that google doc) on how they can better structure their own prompts. Also, another sub-issue in this thread is adding the size limit or chunking, which could be something that breaks our code. The third sub-issue is implementing programming language file parsing. Right now only pdfs, txt, and docx are supported because these are common and easy to implement. It would be nice to upload programming language files as opposed to copying the code into a text box (though not the end of the world). I am going to make these three issues so that I can close this outdated issue (no work was done on it in a month).
