### ISSUE TITLE
Tutorial for React

### ISSUE THREAD

**Issue by TjRaffert** [alejmedinajr/AI-Detector#17]
https://www.youtube.com/watch?v=DgRrrOt0Vr8

**Comment by TjRaffert** [comment]
https://www.youtube.com/watch?v=SqcY0GlETPk I am working on this tutorial.

**Comment by TjRaffert** [comment]
I have watched 35 minutes of this react tutorial. From this video, I have learned that it is an open sourced javascript library for user interfaces. I also learned how to set up the development environment. I think this was a good choice for the framework of our application.

**Comment by TjRaffert** [comment]
The last 30 minutes of the tutorial have been about handling events and managing states. I think these are vital in the creation of our application. I know @alejmedinajr has done some work already so I will discus with him what we are using.

**Comment by alejmedinajr** [comment]
@TjRaffert The code in the repository currently uses events to change the state of the user input (from an empty string to the input of a form when the form is submitted). I still need to go and add documentation to the react project, but it should still be pretty readable since it draws on HTML and JavaScript which was something we saw in Database Management (in case you wanted to go ahead and check that out).

**Comment by TjRaffert** [comment]
I spent the last 30 minutes watching them create components and alerts. This was helpful because I think we are going to have a ton of different types of buttons. They also go over alerts which I don't think we need to mess with just yet but could be useful later on.

**Comment by TjRaffert** [comment]
I spent an hour looking into all the updates @alejmedinajr provided. We used create-react-app which is a command line interface tool from meta for creating React projects. It took me a long time to understand the file structure and really get a handle on how it worked based on the descriptions from create-react-app.
