### ISSUE TITLE
Sign out button leads to white page

### ISSUE THREAD

**Issue by alejmedinajr** [alejmedinajr/AI-Detector#70]
The sign out button leads to an empty blank page, which is not ideal. It needs to lead back to the login form.

**Comment by TjRaffert** [comment]
I have started working on this.

**Comment by TjRaffert** [comment]
I have worked 30 minutes trying to figure out why the navigate function isn't working,

**Comment by TjRaffert** [comment]
I worked another 45 minutes I am still lost on this issue and our old way of testing doesn't work since deployment. https://inspectai.web.app/ is the url for when you pull up the site and it shows the login page. When you signout it sends you to the url https://inspectai.web.app/login which is blank we will examine this in class.

**Comment by TjRaffert** [comment]
I am still working on this will have it done by tonight

**Comment by alejmedinajr** [comment]
Closing this issue because @Caleb-Highsmith addressed it in #93 pull request (which is now in main).
