### ISSUE TITLE
Test Full App 

### ISSUE THREAD

**Issue by Caleb-Highsmith** [alejmedinajr/AI-Detector#96]
We need to test the functionality of the whole app and find any bugs.

**Comment by Caleb-Highsmith** [comment]
Starting this ticket.

**Comment by Caleb-Highsmith** [comment]
Ok so potentially found an issue with gemini responses specifically where the simple print technique gets mad when a response contains complicated texts essentially. Going to try a fix now.

**Comment by Caleb-Highsmith** [comment]
Fixed it. Everything looks good text comparison wise. I was able to full generate a report.

The only thing is that when a user hits generate report it brings them to the account home page with no information. I will add a proper redirect to the report page instead.

**Comment by Caleb-Highsmith** [comment]
I added the redirect to the report page instead because I think that makes sense. I stressed test the text to text comparison but I have some local issues with the file upload so I might have @alejmedinajr test that instead so I can focus on other issues. I did refactor the gemini API call because the way that they parse that can be a pain once we go to display it. I basically fixed it from throwing stupid Gemini errors that make no sense. 

I also tested everything else so here is a quick list:

- Login works
- Sign out on all pages works
- Create Account works (Also there is a cool modal that I added that shows a success message upon account creation :D)
- Prompt page text to text works
- All redirects work (Navigation from prompt to report etc. 
- All help modals work (Good job! @noahzamarripa )
- Reset password works. Also displays proper error messages if the email does not exist
- Generate report works 
- All toggles work (Light and Dark mode plus Chat to Gemini toggles for prompt form and report history) 
- Updating the fields on the user account page works. This is updating the name and email specifically 

Here is what we NEED to test:
Prompt page file to file functionality for both generating a response and generating a report. @alejmedinajr could you do this? 

Lastly, I am going to put a PR for this since I fixed the stupid google gemini errors (they are actually so dumb I can't get over it)

**Comment by alejmedinajr** [comment]
@Caleb-Highsmith Great testing! I agree, the modals are a very nice addition (kudos to @noahzamarripa ). In terms of the generate report, I also saw this, and I just committed to main behavior that instead alerts the user that it could take some time, then alerts the user when it is ready (both using toast). I did leave it on the prompt page though, mainly because it could be confusing to go to the report page when its still loading, especially if the report takes more than 5 minutes to create. I also tested the file to file functionality and it works in mixed mode and file-file.
